package de.milltree.liquibaseexample.extensions;

import liquibase.change.custom.CustomTaskChange;
import liquibase.change.custom.CustomTaskRollback;
import liquibase.database.Database;
import liquibase.exception.CustomChangeException;
import liquibase.exception.RollbackImpossibleException;
import liquibase.exception.SetupException;
import liquibase.exception.ValidationErrors;
import liquibase.resource.ResourceAccessor;

/**
 * Simple example of a {@link CustomTaskChange} which can perform any Java code
 * without the need to create SQL statements as result.
 * <p>
 * Be aware that this kind of change cannot be included in update SQL files
 * generated by Liquibase.
 * </p>
 */
public class PrintText implements CustomTaskChange, CustomTaskRollback {

	@SuppressWarnings("unused")
	private ResourceAccessor resourceAccessor;

	private String text;

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Override
	public String getConfirmationMessage() {
		return "Printed text: " + text + ".";
	}

	@Override
	public void setUp() throws SetupException {
	}

	@Override
	public void setFileOpener(ResourceAccessor resourceAccessor) {
		this.resourceAccessor = resourceAccessor;
	}

	@Override
	public ValidationErrors validate(Database database) {
		ValidationErrors errors = new ValidationErrors();
		errors.checkRequiredField("text", text);
		return errors;
	}

	@Override
	public void execute(Database database) throws CustomChangeException {
		System.out.println(text);
	}

	@Override
	public void rollback(Database database) throws CustomChangeException,
			RollbackImpossibleException {
		System.out.println("Rollback: " + text);
	}

}
